# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d77657af1a01f19e6266a00968bb5d5e6c7e3de60bf595b629d1183d2b2e96bb8a4a66d2725432872ae454f2212a716608df91571562e48bc9c1a21bdfacd2d6

test:
  secret_key_base: 3333f677a05a30c8ed5f7f7599104f3cc7cdfa065f63a57575b8f0b6e618901e60a357470e6d503dc88a758b3e04b462bf688e91267c0c2fe089f1cb0ee2e654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
